name: Doxygen Documentation

on:
  push:
    branches:
      - main  

jobs:
  doxygen:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: brew install doxygen
        # Uses Homebrew to install Doxygen on macOS

      - name: Generate Doxygen documentation
        run: doxygen Doxyfile
        # Ensure Doxyfile is in the root of your repository or specify the correct path.

      - name: Upload documentation as artifact
        uses: actions/upload-artifact@v3
        with:
          name: doxygen-docs
          path: ./html  # Adjust this path if your Doxygen output is located elsewhere
